export const SET_FRIENDS = 'SET_FRIENDS';
export const INIT_GET_FRIENDS = 'INIT_GET_FRIENDS'
export const UPDATE_FRIEND_LIST = 'UPDATE_FRIEND_LIST';
export const UPDATE_FRIEND_TYPING = 'UPDATE_FRIEND_TYPING';

export const INIT_GET_REQUESTS = 'INIT_GET_REQUESTS';
export const SET_REQUESTS = 'SET_REQUESTS';
export const UPDATE_FRIEND_REQUEST = 'UPDATE_FRIEND_REQUEST';
export const ADD_REQUEST = 'ADD_REQUEST';

export const SET_CURRENT_FRIEND = 'SET_CURRENT_FRIEND';

export const INIT_GET_MESSAGES = 'INIT_GET_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_MESSAGES_READ_STATUS = 'UPDATE_MESSAGES_READ_STATUS';

export const USER_LOGOUT = 'USER_LOGOUT';